name: Run codeception

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Validate composer.json and composer.lock
      working-directory: ./wp-content/plugins/my-plugin
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      working-directory: ./wp-content/plugins/my-plugin
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run chrome driver
      run: nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &
    
    - name: Run codeception test
      working-directory: ./wp-content/plugins/my-plugin
      run: vendor/bin/codecept run acceptance --steps